In [52]:
import numpy as np

In [6]:
data = [[1,2,3],[4,5,6],[7,8,9]]

a= np.array(data)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
a.dtype

dtype('int32')

In [9]:
a = a.astype(np.float32) #a = a.astype('float32')
a

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float32)

In [10]:
a[0][1]

2.0

In [11]:
a[0]

array([1., 2., 3.], dtype=float32)

In [12]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [13]:
np.arange(1,10).reshape(3, 3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
np.arange(1,13).reshape(3, 2, 2)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [17]:
np.nan * 10

nan

In [19]:
a = np.linspace(1,10)
a

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [22]:
data = np.arange(1,10).reshape(3,3)  # 형태변환
data

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
[1,2,3] + [4,5,6]

[1, 2, 3, 4, 5, 6]

In [26]:
data@data

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [29]:
# 0차원 : 스칼라
a = np.array(1)
a
a.shape
a.ndim

0

In [31]:
# 1차원 : 벡터
a =np.array([1])
a
a.shape
a.ndim

1

In [33]:
# 2차원 : 메트릭스
a =np.array([[1,2,3], [4,5,6]])
a
a.shape
#a.ndim

(2, 3)

In [36]:
# 3차원 : 3차원 이상의 다차원의 행렬을 Tensor
a = np.array([[[1,2],[3,4],[5,6],[7,8]]])
a
# 텐서플로우 : 다차원
a.shape
a.ndim # 차원

3

In [38]:
a = np.arange(12).reshape(2,3,2)
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [41]:
b = np.ones(12)
b

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [43]:
b = np.zeros(12)
b

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [45]:
d = np.eye(3) #단위행렬
d

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [48]:
rawData = np.random.randint(50,100, size=(4,3))
rawData

array([[69, 94, 58],
       [70, 73, 67],
       [87, 76, 85],
       [82, 95, 64]])

In [55]:
import pandas as pd

df = pd.DataFrame(rawData,
                  index=['1반', '2반', '1반', '2반'],
                  columns=['국','영','수'])
df

국   영   수
1반  69  94  58
2반  70  73  67
1반  87  76  85
2반  82  95  64

In [57]:
df['국']

1반    69
2반    70
1반    87
2반    82
Name: 국, dtype: int32

In [58]:
#df[0] > error 

In [59]:
df['평균'] = round((df['국']+df['영']+df['수'])/3 ,2)
df

국   영   수     평균
1반  69  94  58  73.67
2반  70  73  67  70.00
1반  87  76  85  82.67
2반  82  95  64  80.33